apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-deployment
spec:
  selector:
    matchLabels:
      app: trading
  template:
    metadata:
      labels:
        app: trading
        aadpodidbinding: trading
    spec:
      containers:
      - name: trading
        image: dotneteconomy.azurecr.io/dotnet.trading:1.0.2
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS
          - name: ServiceSettings__KeyVaultName
            value: dotneteconomy
          - name: ServiceSettings__Authority
            value: https://dotneteconomy.eastus.cloudapp.azure.com/identity-svc
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5006
        livenessProbe:
          httpGet:
            port: 5006
            path: /health/live
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            port: 5006
            path: /health/ready
          initialDelaySeconds: 10
        
---
apiVersion: v1
kind: Service
metadata:
  name: trading-service
spec:
  type: ClusterIP #Default type for Kubernetes
  selector:
    app: trading
  ports:
  - port: 80
    targetPort: 5006
