# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CICD

on:
  push:
    branches: [ "main" ]

jobs:
  generate-version:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Github Tag Bump
      id: tag_bump
      uses: anothrNick/github-tag-action@1.52.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        INITIAL_VERSION: 1.0.3
        DEFAULT_BUMP: patch
        
    outputs:
      new_version: ${{ steps.tag_bump.outputs.new_tag }}
    
  build-and-deploy-service:

    runs-on: ubuntu-latest
    needs: generate-version
    
    env:
      APP_NAME: dotneteconomy

    steps:
    - uses: actions/checkout@v3
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v3.2.0
      with:
        secrets: |
          "GH_OWNER=${{github.repository_owner}}"
          "GH_PAT=${{secrets.GH_PAT}}"
        tags: ${{env.APP_NAME}}.azurecr.io/dotnet.trading:${{ needs.generate-version.outputs.new_version }}
